### ISSUE TITLE
Error running Python script

### ISSUE THREAD

**Issue by hejaali84** [revoxhere/magi-rest-api#1]
Hello, I've been trying to test out the Coin Magi Python library so I could later incorporate it into my other projects but when I try to run the ["simple program"](https://magi.duinocoin.com/api.html)  It spits out these errors:

Traceback (most recent call last):
  File "C:\Users\toshiba2014\Downloads\Python Script\main.py", line 4, in <module>
    print(magi.statistics())
  File "C:\Users\toshiba2014\Downloads\Python Script\magilib.py", line 160, in statistics
    info = self.magi.getmininginfo()
  File "C:\Users\toshiba2014\AppData\Local\Programs\Python\Python310\lib\site-packages\bitcoinrpc\authproxy.py", line 132, in __call__
    self.__conn.request('POST', self.__url.path, postdata,
  File "C:\Users\toshiba2014\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\toshiba2014\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\toshiba2014\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\toshiba2014\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\toshiba2014\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\toshiba2014\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 941, in connect
    self.sock = self._create_connection(
  File "C:\Users\toshiba2014\AppData\Local\Programs\Python\Python310\lib\socket.py", line 845, in create_connection
    raise err
  File "C:\Users\toshiba2014\AppData\Local\Programs\Python\Python310\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

I have installed python-bitcoinrpc and requests. I have also put in the library in the same folder as the main script. This has made me scratch my head a lot recently so I hope I could get some answers here.

**Comment by hejaali84** [comment]
I have realized this is a problem on the server's side so...

**Comment by revoxhere** [comment]
There's no server side, you need to have your own magi rpc running.
